pub mod theme;
pub mod converter;
use theme::{Theme, COLOR_SCHEME_SIZE};

/// All Alacritty color schemes embedded as bytes.
///
/// The `colorschemes.bin` file is generated by:
/// 1. Downloading `.toml` themes from the repository:
///    https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/alacritty
/// 2. Converting each theme into a `Theme` struct using `converter.rs`.
/// 3. Serializing the themes sequentially into bytes:
///    - `[NAME_SIZE u8]`
///    - `[NAME string]`
///    - `[IS_LIGHT u8]`
///    - `[COLOR_SCHEME bytes]`
///
/// These bytes are included at compile time and deserialized into
/// an array of `Theme` structs at runtime.
pub const COLOR_SCHEMES: &[u8] = include_bytes!("colorschemes.bin");

pub fn rand() -> Theme {
    todo!();
}
