use std::io;
use std::path::PathBuf;
use std::process::Command;

/// Returns the path to the current desktop wallpaper file, if it can be determined.
pub fn desktop_wallpaper_path() -> io::Result<Option<PathBuf>> {
    #[cfg(target_os = "macos")]
    {
        return macos_wallpaper_path();
    }

    #[cfg(any(
        target_os = "linux",
        target_os = "freebsd",
        target_os = "openbsd",
        target_os = "netbsd"
    ))]
    {
        return unix_wallpaper_path();
    }

    #[allow(unreachable_code)]
    Ok(None)
}

#[cfg(target_os = "macos")]
fn macos_wallpaper_path() -> io::Result<Option<PathBuf>> {
    let output = Command::new("osascript")
        .args([
            "-e",
            "tell application \"System Events\" to get picture of current desktop",
        ])
        .output()?;

    if !output.status.success() {
        return Ok(None);
    }

    let raw = String::from_utf8_lossy(&output.stdout);
    let trimmed = raw.trim();

    // osascript returns the literal string "missing value" when no wallpaper is set
    // (e.g. no active desktop/display session).
    if trimmed.is_empty() || trimmed == "missing value" {
        return Ok(None);
    }

    let path = PathBuf::from(trimmed);
    Ok(path.is_file().then_some(path))
}

// Attempts to locate the desktop wallpaper path across common Unix desktop environments
// (GNOME, KDE Plasma, XFCE, MATE, Cinnamon, LXQt).
//
// NOTE: This function was fully generated by AI and has NOT been tested on any real system.
#[cfg(any(
    target_os = "linux",
    target_os = "freebsd",
    target_os = "openbsd",
    target_os = "netbsd"
))]
fn unix_wallpaper_path() -> io::Result<Option<PathBuf>> {
    let desktop = env::var("XDG_CURRENT_DESKTOP")
        .or_else(|_| env::var("DESKTOP_SESSION"))
        .unwrap_or_default()
        .to_lowercase();

    // Try the detected DE first, then fall back through the rest.
    let mut attempts: Vec<fn() -> io::Result<Option<PathBuf>>> = vec![
        gnome_wallpaper,
        kde_wallpaper,
        xfce_wallpaper,
        mate_wallpaper,
        cinnamon_wallpaper,
        lxqt_wallpaper,
    ];

    let priority: Option<fn() -> io::Result<Option<PathBuf>>> = if desktop.contains("kde") {
        Some(kde_wallpaper)
    } else if desktop.contains("xfce") {
        Some(xfce_wallpaper)
    } else if desktop.contains("mate") {
        Some(mate_wallpaper)
    } else if desktop.contains("cinnamon") {
        Some(cinnamon_wallpaper)
    } else if desktop.contains("lxqt") || desktop.contains("lxde") {
        Some(lxqt_wallpaper)
    } else {
        None
    };

    if let Some(p) = priority {
        attempts.retain(|f| *f as usize != p as usize);
        attempts.insert(0, p);
    }

    for attempt in attempts {
        if let Some(path) = attempt()? {
            return Ok(Some(path));
        }
    }

    Ok(None)
}

#[cfg(any(
    target_os = "linux",
    target_os = "freebsd",
    target_os = "openbsd",
    target_os = "netbsd"
))]
fn run_command(cmd: &str, args: &[&str]) -> io::Result<Option<String>> {
    let output = match Command::new(cmd).args(args).output() {
        Ok(o) => o,
        Err(_) => return Ok(None), // binary not installed
    };

    if !output.status.success() {
        return Ok(None);
    }

    Ok(Some(String::from_utf8_lossy(&output.stdout).into_owned()))
}

// Decodes percent-encoded characters (e.g. "%20" -> " ") from a file:// URI.
#[cfg(any(
    target_os = "linux",
    target_os = "freebsd",
    target_os = "openbsd",
    target_os = "netbsd"
))]
fn percent_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let Ok(byte) = u8::from_str_radix(&s[i + 1..i + 3], 16) {
                out.push(byte);
                i += 3;
                continue;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

#[cfg(any(
    target_os = "linux",
    target_os = "freebsd",
    target_os = "openbsd",
    target_os = "netbsd"
))]
fn path_from_uri_or_raw(raw: &str) -> Option<PathBuf> {
    let trimmed = raw.trim().trim_matches('\'').trim_matches('"');
    let stripped = trimmed.strip_prefix("file://").unwrap_or(trimmed);
    let decoded = percent_decode(stripped);
    let path = PathBuf::from(decoded);
    path.is_file().then_some(path)
}

#[cfg(any(
    target_os = "linux",
    target_os = "freebsd",
    target_os = "openbsd",
    target_os = "netbsd"
))]
fn gnome_wallpaper() -> io::Result<Option<PathBuf>> {
    for key in ["picture-uri", "picture-uri-dark"] {
        if let Some(raw) = run_command("gsettings", &["get", "org.gnome.desktop.background", key])?
        {
            if let Some(path) = path_from_uri_or_raw(&raw) {
                return Ok(Some(path));
            }
        }
    }
    Ok(None)
}

#[cfg(any(
    target_os = "linux",
    target_os = "freebsd",
    target_os = "openbsd",
    target_os = "netbsd"
))]
fn mate_wallpaper() -> io::Result<Option<PathBuf>> {
    match run_command(
        "gsettings",
        &["get", "org.mate.background", "picture-filename"],
    )? {
        Some(raw) => Ok(path_from_uri_or_raw(&raw)),
        None => Ok(None),
    }
}

#[cfg(any(
    target_os = "linux",
    target_os = "freebsd",
    target_os = "openbsd",
    target_os = "netbsd"
))]
fn cinnamon_wallpaper() -> io::Result<Option<PathBuf>> {
    match run_command(
        "gsettings",
        &["get", "org.cinnamon.desktop.background", "picture-uri"],
    )? {
        Some(raw) => Ok(path_from_uri_or_raw(&raw)),
        None => Ok(None),
    }
}

#[cfg(any(
    target_os = "linux",
    target_os = "freebsd",
    target_os = "openbsd",
    target_os = "netbsd"
))]
fn xfce_wallpaper() -> io::Result<Option<PathBuf>> {
    let list = match run_command("xfconf-query", &["-c", "xfce4-desktop", "-l"])? {
        Some(l) => l,
        None => return Ok(None),
    };

    // Property paths vary per monitor/workspace, e.g. .../monitor0/workspace0/last-image.
    for line in list.lines() {
        if line.contains("last-image") || line.contains("image-path") {
            if let Some(raw) =
                run_command("xfconf-query", &["-c", "xfce4-desktop", "-p", line.trim()])?
            {
                if let Some(path) = path_from_uri_or_raw(&raw) {
                    return Ok(Some(path));
                }
            }
        }
    }
    Ok(None)
}

#[cfg(any(
    target_os = "linux",
    target_os = "freebsd",
    target_os = "openbsd",
    target_os = "netbsd"
))]
fn kde_wallpaper() -> io::Result<Option<PathBuf>> {
    // Only fetch the image path; no extra print statements to avoid stray output lines.
    let script = r#"
        var d = desktops()[0];
        d.currentConfigGroup = ["Wallpaper", "org.kde.image", "General"];
        print(d.readConfig("Image"));
    "#;

    for bin in ["qdbus", "qdbus6", "qdbus-qt5"] {
        let out = run_command(
            bin,
            &[
                "org.kde.plasmashell",
                "/PlasmaShell",
                "org.kde.PlasmaShell.evaluateScript",
                script,
            ],
        )?;

        if let Some(raw) = out {
            // Take the last non-empty line in case of extra output.
            if let Some(last) = raw.lines().rev().find(|l| !l.trim().is_empty()) {
                if let Some(path) = path_from_uri_or_raw(last) {
                    return Ok(Some(path));
                }
            }
        }
    }

    Ok(None)
}

#[cfg(any(
    target_os = "linux",
    target_os = "freebsd",
    target_os = "openbsd",
    target_os = "netbsd"
))]
fn lxqt_wallpaper() -> io::Result<Option<PathBuf>> {
    let home = env::var("HOME").unwrap_or_default();
    let env_name = env::var("LXQT_DE_ENV").unwrap_or_default();

    // Config subfolder name varies across distros; try known variants.
    let mut candidates = vec!["lxqt".to_string(), "LXQt".to_string()];
    if !env_name.is_empty() {
        candidates.insert(0, env_name);
    }

    for name in candidates {
        let config_path = PathBuf::from(format!("{home}/.config/pcmanfm-qt/{name}/settings.conf"));
        let content = match std::fs::read_to_string(&config_path) {
            Ok(c) => c,
            Err(_) => continue,
        };

        for line in content.lines() {
            if let Some(value) = line.trim().strip_prefix("Wallpaper=") {
                let path = PathBuf::from(value.trim());
                if path.is_file() {
                    return Ok(Some(path));
                }
            }
        }
    }

    Ok(None)
}
